workflows:
  flutter-app:
    name: Flutter Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_TARGET: "lib/main.dart"
        SUPABASE_URL: Encrypted(...)
        SUPABASE_ANON_KEY: Encrypted(...)
      groups:
        - supabase_credentials
      android_signing:
        - keystore_reference
      ios_signing:
        - provisioning_profiles
        - certificate
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
    scripts:
      - name: Get Dependencies
        script: |
          flutter pub get

      - name: Build APK
        script: |
          flutter build apk --release

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - your-email@example.com